---

- hosts: all
  become: true
  pre_tasks: 

  - name: update repo cache (RedHat)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"
 
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"    

- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOO1iJ/Whcqt9k5opDU4/XhF5CtOnXVg7bKwpH0niH86 ansible"

- hosts: web_servers
  become: true
  tasks:  

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for Redhat servers
    tags: httpd,RedHat,apache
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start the httpd service (RedHat)
    tags: apache,RedHat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: change the email address for admin
    tags: apache,RedHat,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "RedHat"
    register: httpd
  
  - name: restart httpd (RedHat)
    tags: apache,RedHat,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy the default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0775
      owner: root
      group: root

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: RedHat,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"


  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest








