---

- hosts: all
  become: true
  pre_tasks: 

  - name: update repo cache (RedHat)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"
 
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"    

- hosts: all
  become: true
  roles:
    - base 

- hosts: workstation
  become: true
  roles:
    - workstation  

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers  




