- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0775
    owner: root
    group: root

